# number of concurrent user sessions, optional parameter, default 1
concurrency: 1000

# number of script repetitions, optional parameter, default 1
loopcount: 10

# time to wait for a response from the server, optional parameter, by default 2 seconds
timeout: 5

# network protocol http or https, optional parameter, default http
scheme: https

# domain hostname or IP address, required parameter
host: example.com

# host port for connection, optional parameter, default 80
port: 8080

randomdelayms: 200

# variables can be used in header, request variable
params:
  # regular variables are selected for each request and are not related in any way
  search:
    # if the value is an enumeration, then one of the enumeration values ​​will be substituted into the request
    languages: [php, java, c++, c, go, golang, js]
    structures: [for, while, class, if, else, case]
  agent:
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36 FirePHP/4Chrome
    - Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
    - Mozilla/5.0 (compatible; MSIE 10.6; Windows NT 6.1; Trident/5.0; InfoPath.2; SLCC1; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 2.0.50727) 3gpp-gba UNTRUSTED/1.0
    - Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0
  say: hello world

  # global headers to be inserted in every script request, optional parameter
  session:
    - login: user1
      password: password1
      friendIds: [1, 2, 3, 4]
    - login: user2
      password: password2
      friendIds: [5, 6, 7, 8]


# глобальные заголовки, которые будут вставлены в каждый запрос сценария,
# необязательный параметр
# global headers to be inserted in every script request, optional parameter
headers:
  Content-Type: text/html; charset=utf-8
  User-Agent: ${agent}
  X-Key-1: Value-1

# timeout for a response from the server of this request, optional parameter, by default the global timeout will be used
requests:

  # GET|POST|PUT|DELETE: /path?query - стандартные запросы

  - GET: /index

  - POST: /signin
    # optional POST parameters
    params:
      login: ${session.login}
      password: ${session.password}
    # timeout for a response from the server of this request, optional parameter, by default the global timeout will be used
    timeout: 10

  - GET: /profile
    # this request headers, optional
    headers:
      # will overwrite the value of the global header to local
      X-Key-1: New-Value-1
      X-Key-2: Value-2

  # RANDOM | SYNC - request groups

  # RANDOM - in this group, requests will be executed in an arbitrary order an arbitrary number of times (some request may be executed several times, and some will not be executed at all)
  - RANDOM:
    - GET: /some/path?query=1
    - GET: /some/path/2?query=12
    - POST: /some/path/save
      params:
        friend_id: ${session.friendIds}
        say: ${say}

    # to send raw json body you have to specify request's raw_body in params AND set content-type headers to application/json
    - POST: /json/data/receiver
      params:
        raw_body: |
          {"token":"ololo","key_id":"trololo"}
      headers:
          Content-type: application/json

    # SYNC - in this group all requests will be executed in the order in which they are specified. SYNC can be both inside and outside RANDOM.
    - SYNC:
      - GET: /some/path?query=2
      - GET: /some/path/3?query=123

